### ISSUE TITLE
Crash on breaking Firefly Lantern

### ISSUE THREAD

**Issue by Entrivax** [Better-than-Adventure/bta-issues#267]
**Describe the bug**
Minecraft crashes when breaking a (green) Firefly Lantern with an empty hand.

**To Reproduce**
1. Join a world (singleplayer or multiplayer)
2. Place a Lantern
3. In survival mode, without holding anything, break the lantern
4. Game crashes

**Version info (please complete the following information):**
 - Version 1.7.7.0_01

**Crash Logs**
--- BEGIN ERROR REPORT db2068b5 --------
Generated 8/16/23, 11:19 PM

Minecraft: Better than Adventure! 1.7.7.0_01
OS: Windows 11 (amd64) version 10.0
Java: 17.0.6, Eclipse Adoptium
VM: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
LWJGL: 2.9.4
OpenGL: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 version 4.6.0 NVIDIA 528.49, NVIDIA Corporation

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.item.Item.isSilkTouch()" because "item" is null
	at net.minecraft.core.block.BlockLanternFirefly.onBlockDestroyedByPlayer(BlockLanternFirefly.java:146)
	at net.minecraft.client.player.controller.PlayerController.destroyBlock(PlayerController.java:158)
	at net.minecraft.client.player.controller.PlayerControllerMP.destroyBlock(PlayerControllerMP.java:30)
	at net.minecraft.client.player.controller.PlayerController.mine(PlayerController.java:118)
	at net.minecraft.client.Minecraft.mineBlocks(Minecraft.java:969)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1525)
	at net.minecraft.client.Minecraft.run(Minecraft.java:694)
	at java.base/java.lang.Thread.run(Thread.java:833)
--- END ERROR REPORT 2e04507c ----------

**Comment by bestsoft100** [comment]
Fixed
