### ISSUE TITLE
audio bug 7.1

### ISSUE THREAD

**Issue by 009ben00** [Better-than-Adventure/bta-issues#317]
**Describe the bug**
game don't have a sound . I  reinstalled  it not change it  . if I try change the audio game will crash

**To Reproduce**
1. Go to 'open the game'
2. Click on 'options , audio , change some audio  '
3. Scroll down to '(do not have)'

**Expected behavior**
I don't know a lot but I am on prism launcher I guess a file my launcher cant read or my pc 

**Screenshots**
is only the error this are missing ( the background )

 I can't get a screenshot form background screen I whiten "missingtex"

**Version info (please complete the following information):**
 - Version [e.g. 7.1

**Additional context**
loading , setting , world select , server select don't have the background image

**Crash Logs** 
( I put the error here )

Minecraft: Better than Adventure! 7.1
OS: Windows 8.1 (amd64) version 6.3
Java: 1.8.0_51, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 630 version 4.6.0 - Build 30.0.101.1338, Intel

java.lang.NoClassDefFoundError: paulscode/sound/SoundSystem
    at net.minecraft.client.option.VolumeOption.onUpdate(VolumeOption.java:21)
    at net.minecraft.client.gui.options.components.FloatOptionComponent.resetValue(FloatOptionComponent.java:62)
    at net.minecraft.client.gui.options.components.ButtonComponent.onMouseClick(ButtonComponent.java:68)
    at net.minecraft.client.gui.options.components.OptionsCategory.onMouseClick(OptionsCategory.java:114)
    at net.minecraft.client.gui.options.GuiOptions.mouseClicked(GuiOptions.java:415)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:131)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1208)
    at net.minecraft.client.Minecraft.run(Minecraft.java:792)
    at java.lang.Thread.run(Unknown Source)

**Comment by jonkadelic** [comment]
You've installed BTA wrong. Use "add to jar" in prism launcher, not "replace jar".

**Comment by 009ben00** [comment]
> You've installed BTA wrong. Use "add to jar" in prism launcher, not "replace jar".

I use zip file ?

**Comment by 009ben00** [comment]
i did what you say 

Minecraft ran into an unexpected problem that it cannot recover from!

The current game has quit, please restart the game.

If you wish to report this, please copy this entire text and post it on the forum thread at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/3106066-better-than-adventure-for-beta-1-7-3-timely, or join the Discord server at https://betterthanadventure.net/discord and post it in #bug-reports.

Generated 4/19/24 5:54 PM

Minecraft: Better than Adventure! 7.1
OS: Windows 8.1 (amd64) version 6.3
Java: 1.8.0_51, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 630 version 4.6.0 - Build 30.0.101.1338, Intel

java.lang.NoClassDefFoundError: paulscode/sound/SoundSystem
    at net.minecraft.client.option.VolumeOption.onUpdate(VolumeOption.java:21)
    at net.minecraft.client.gui.options.components.FloatOptionComponent.buttonClicked(FloatOptionComponent.java:26)
    at net.minecraft.client.gui.options.components.ButtonComponent.onMouseClick(ButtonComponent.java:65)
    at net.minecraft.client.gui.options.components.OptionsCategory.onMouseClick(OptionsCategory.java:114)
    at net.minecraft.client.gui.options.GuiOptions.mouseClicked(GuiOptions.java:415)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:131)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1208)
    at net.minecraft.client.Minecraft.run(Minecraft.java:792)
    at java.lang.Thread.run(Unknown Source)

Go to 'open the game'
Click on 'options , audio , change some audio '
Scroll down to '(do not have)'
See error

game still have no sound .
help ?
